Jukebox.Razor/Pages/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Jukebox.Database;

namespace Jukebox.Razor.Pages;
public class EditModel : PageModel {
    private readonly JukeboxDbContext db;
    public EditModel(JukeboxDbContext db) {
        this.db = db ?? throw new ArgumentNullException(nameof(db));
    }
    [BindProperty]
    public string TrackName { get; set; } = "";

    [BindProperty]
    public string ArtistName { get; set; } = "";

    [BindProperty(SupportsGet = true)]
    public Guid TrackId { get; set; }
    public async Task<IActionResult> OnGet() {
        var track = await this.db.Tracks.SingleOrDefaultAsync(x => x.TrackId == TrackId);
        if (track == null) {
            return NotFound();
        }

        TrackName = track.TrackName;
        ArtistName = track.ArtistName;

        return Page();
    }
    public async Task<IActionResult> OnPost() {
        var track = await this.db.Tracks.SingleOrDefaultAsync(x => x.TrackId == TrackId);
        if (track == null) {
            return NotFound();
        }

        this.db.Tracks.Remove(track);
        await this.db.SaveChangesAsync();

        return RedirectToPage("Tracks");
    }
}

Jukebox.Razor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Jukebox.Razor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Jukebox.Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Jukebox.Razor.Pages;

public class IndexModel : PageModel
{
    private readonly Jukebox.Core.Jukebox jukebox;
    public IndexModel(Jukebox.Core.Jukebox jukebox) {
        this.jukebox = jukebox ?? throw new ArgumentNullException(nameof(jukebox));
    }

    public void OnGet() {
        CurrentTrack = this.jukebox.CurrentlyPlaying.Match<Jukebox.Core.Track?>(x => x , _ => null);
        CurrentQueue = this.jukebox.CurrentQueue();
        IsPlaying = this.jukebox.IsPlaying;
    }
    public bool IsPlaying { get; private set; }
    public Jukebox.Core.Track? CurrentTrack { get; set; }
    public IReadOnlyList<Jukebox.Core.Track> CurrentQueue { get; set; } = new List<Jukebox.Core.Track>();

    public IActionResult OnPostPlay() {
        this.jukebox.Play();
        return RedirectToPage("Index");
    }
    public IActionResult OnPostPause() {
        this.jukebox.Pause();
        return RedirectToPage("Index");
    }
    public async Task<IActionResult> OnPostSkip() {
        this.jukebox.Skip();
        await Task.Delay(250); //artificial delay as libVLC doesn't say currently playing immediately
        return RedirectToPage("Index");
    }
}

Jukebox.Razor/Pages/New.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Jukebox.Database;

namespace Jukebox.Razor.Pages;
public class NewModel : PageModel {
    private readonly JukeboxDbContext db;
    public NewModel(JukeboxDbContext db) {
        this.db = db ?? throw new ArgumentNullException(nameof(db));
    }
    [BindProperty, Required]
    public string TrackName { get; set; } = "";

    [BindProperty, Required]
    public string ArtistName { get; set; } = "";
    
    [BindProperty, Required]
    public IFormFile? Upload { get; set; }

    public void OnGet() { }
    public async Task<IActionResult> OnPost() {
        if (!ModelState.IsValid) {
            return Page();
        }
        if (Upload is null) { throw new ArgumentNullException(nameof(Upload)); }

        using var stream = new System.IO.MemoryStream();
        await Upload.CopyToAsync(stream);

        this.db.Tracks.Add(new Jukebox.Database.Track() {
            TrackName = TrackName,
            ArtistName = ArtistName,
            File = new TrackFile() {
                FileData = stream.ToArray()
            }
        });

        await this.db.SaveChangesAsync();

        return RedirectToPage("Index");
    }
}

Jukebox.Razor/Pages/Tracks.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Jukebox.Database;

namespace Jukebox.Razor.Pages
{
    public class TracksModel : PageModel
    {
        private readonly JukeboxDbContext db;
        private readonly Jukebox.Core.Jukebox jukebox;
        public TracksModel(JukeboxDbContext db, Jukebox.Core.Jukebox jukebox) {
            this.db = db ?? throw new ArgumentNullException(nameof(db));
            this.jukebox = jukebox ?? throw new ArgumentNullException(nameof(jukebox));
        }
        public IList<Track> Tracks { get; set; } = new List<Track>();
        public async Task OnGetAsync () {
            Tracks = await this.db.Tracks.ToListAsync();
        }
        public async Task<IActionResult> OnPostAsync(Guid id) {
            var track = await this.db.Tracks.Include(x => x.File).SingleAsync(x => x.TrackId == id);
            this.jukebox.Enqueue(new Jukebox.Core.Track(track.TrackId, track.TrackName, track.ArtistName, track.File.FileData));
            await Task.Delay(250); //artificial delay as libVLC doesn't say currently playing immediately
            return RedirectToPage("Index");
        }
    }
}

Jukebox.Razor/Pages/Edit.cshtml
@page
@model Jukebox.Razor.Pages.EditModel
@{
}

<h2>Edit Track</h2>

<form method="post">
    <div class="mb-3">
        <label>Track Name</label>
        <input class="form-control" asp-for="TrackName" readonly />
        <span asp-validation-for="TrackName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label>Artist Name</label>
        <input class="form-control" asp-for="ArtistName" readonly />
        <span asp-validation-for="ArtistName" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Jukebox.Razor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@if (Model.CurrentTrack is null) {
  <h3>Nothing Playing</h3>
}
else {
  <div class="row">
    <div class="col">
      @if (Model.IsPlaying) {
        <form method="post" asp-page-handler="Pause">
          <button type="submit" class="btn btn-outline-primary float-end" id="pause">
            <i class="bi bi-pause-fill" style="font-size: 3rem;"></i>
          </button>
        </form>
      }
      else {
        <form method="post" asp-page-handler="Play">
          <button type="submit" class="btn btn-outline-primary float-end" id=play>
            <i class="bi bi-play-fill" style="font-size: 3rem;"></i>
          </button>
        </form>
      }
    </div>
    <div class="col">
      @if (Model.CurrentQueue.Count > 0) {
        <form method="post" asp-page-handler="Skip">
          <button type="submit" class="btn btn-outline-primary" id="skip">
            <i class="bi bi-skip-end-fill" style="font-size: 3rem;"></i>
          </button>
        </form>
      } 
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col">
      <h3>Currently Playing</h3>
      <div class="ms-2 me-auto" id="currentlyPlaying">
        <div class="fw-bold">@Model.CurrentTrack.Name</div>
        @Model.CurrentTrack.ArtistName
      </div>
    </div>
  </div>
}

@if (@Model.CurrentQueue.Count > 0) {
  <br />
  <div class="row">
    <div class="col">
      <h3>Up Next</h3>
      <ul class="list-group list-group-flush">
        @foreach (var track in Model.CurrentQueue) {
          <li class="list-group-item">
            <div class="ms-2 me-auto">
              <div class="fw-bold">@track.Name</div>
              @track.ArtistName
            </div>
          </li>
        }
      </ul>
    </div>
  </div>
}

Jukebox.Razor/Pages/New.cshtml
@page
@model Jukebox.Razor.Pages.NewModel
@{
}

<h2>Upload Track</h2>

<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label>Track Name</label>
        <input class="form-control" asp-for="TrackName" />
        <span asp-validation-for="TrackName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label>Artist Name</label>
        <input class="form-control" asp-for="ArtistName" />
        <span asp-validation-for="ArtistName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label>File</label>
        <input type="file" class="form-control" asp-for="Upload" />
        <span asp-validation-for="Upload" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Jukebox.Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jukebox.Razor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jukebox.Razor.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Jukebox</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Tracks">Track List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/New">Upload Track</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Jukebox
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Jukebox.Razor/Pages/Tracks.cshtml
@page
@model Jukebox.Razor.Pages.TracksModel
@{
}

<h2>Track List</h2>

<table class="table">
    <thead>
        <tr>
            <th>Track Name</th>
            <th>Artist Name</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tracks) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TrackName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArtistName)
                </td>
                <td>
                    <a asp-page="/Edit" asp-route-trackid="@item.TrackId" class="btn btn-link">Edit</a>
                </td>
                <td>
                    <form method="post">
                        <input type="hidden" name="id" value="@item.TrackId" />
                        <button class="btn btn-primary" type="submit"><i class="bi bi-music-note"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>